spring:
  application:
    name: hkhj4Service
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  profiles:
    active: dev
server:
  port: 8080
logging:
  level:
    root: info
pay_key: 1xa6FEwJ7mc1iKxAdtvjGGTcYmo3j9NP