spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hkhj4?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
    username: admin
    password: wxwxhn13.
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000

  devtools:
    restart:
      enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: hkhj4_2026_secure_key_12345678901234567890
  expire: 3600000

logging:
  level:
    root: WARN
    com.hkhj4: INFO

  file:
    name: /var/log/hkhj4Service/app.log

  logback:
    rolling policy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.log"
      max-file-size: 100MB
      max-history: 30

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: false