spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/hkhj4?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: admin
    password: password

  data:
    redis:
      host: 192.168.1.3
      port: 6379
      database: 0
      connect-timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
  mail:
    host: smtp.qq.com
    username: 1772081518@qq.com
    password: lyxghmojogolbejd
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
        debug: true

jwt:
  secret: hkhj4_2026_secure_key_12345678901234567890
  expire: 3600000

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  level:
    com.hkhj4.mapper: DEBUG